name: biteline
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAY-BLACK-ITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAY-BOLD.OTF
        - asset: assets/fonts/SFPRODISPLAY-HEAVY-ITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAY-LIGHT-ITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAY-MEDIUM.OTF
        - asset: assets/fonts/SFPRODISPLAY-REGULAR.OTF
        - asset: assets/fonts/SFPRODISPLAY-SEMIBOLD-ITALIC.OTF
        - asset: assets/fonts/SFPRODISPLAY-THINI-TALIC.OTF
        - asset: assets/fonts/SFPRODISPLAY-ULTRALIGHT-ITALIC.OTF
