name: biteline
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAY-BLACK-ITALIC.ttf
        - asset: assets/fonts/SFPRODISPLAY-BOLD.ttf
        - asset: assets/fonts/SFPRODISPLAY-HEAVY-ITALIC.ttf
        - asset: assets/fonts/SFPRODISPLAY-LIGHT-ITALIC.ttf
        - asset: assets/fonts/SFPRODISPLAY-MEDIUM.ttf
        - asset: assets/fonts/SFPRODISPLAY-REGULAR.ttf
        - asset: assets/fonts/SFPRODISPLAY-SEMIBOLD-ITALIC.ttf
        - asset: assets/fonts/SFPRODISPLAY-THINI-TALIC.ttf
        - asset: assets/fonts/SFPRODISPLAY-ULTRALIGHT-ITALIC.ttf
